### ISSUE TITLE
Add support for gradle

### ISSUE THREAD

**Issue by MichelMelhem** [rototor/pdfbox-graphics2d#23]
Hello,
Can you please add support for Gradle because I want to use this lib with pdfbix-android.
Thank you

**Comment by rototor** [comment]
Sorry, but what you want has nothing to do with Gradle, because the build system is not the problem you are facing if you want to use this library with Android. 

- PDFBox-Android is based on an old outdated PDFBox 1.8.10 release (1.8.17 is current), this project is based on the current PDFBox 2.0
- There is no java.awt.Graphics2D in Android. If I understand it correctly the nearest thing to Graphics2D on Android is android.graphics.Canvas.

So you likely want a "pdfbox-canvas" adapter for use on Android. This is something which is out of scope for this project. Feel free to create such an adapter and borrow as much code as you can from this project. I have no idea if this will work as pdfbox-android is likely missing many features from PDFBox 2.0.
