### ISSUE TITLE
Fonts are rasterized despite being a registered font

### ISSUE THREAD

**Issue by DaveJarvis** [rototor/pdfbox-graphics2d#30]
## Overview

Attempting to render an SVG file read from Batik onto an exported PDF document has encountered a few problems, including:

* Font rasterization
* Font weights
* Grid marks
* Colour

## Versions

* Apache PDFBox 2.0.22
* Apache Batik 1.14
* PDF Graphics 2D 0.31
* OpenJDK 15
* Linux kernel 5.9.14, XFCE on Arch

## Fonts

* Roboto, Roboto Thin - https://fonts.google.com/specimen/Roboto?preview.text_type=custom
* Daggersquare - https://www.dafont.com/daggersquare.font

The call to `graphics.setFontTextDrawer( sFontTextDrawer );` didn't seem to make a difference. Here are the relevant font paths printed by the SSCCE and font names printed using `fc-scan`:

```
GOOG: Roboto,Roboto Medium -- /home/username/.fonts/ttf/Roboto-Medium.ttf
GOOG: Roboto,Roboto Thin -- /home/username/.fonts/ttf/Roboto-ThinItalic.ttf
GOOG: Roboto -- /home/username/.fonts/ttf/Roboto-Regular.ttf
GOOG: Roboto,Roboto Black -- /home/username/.fonts/ttf/Roboto-Black.ttf
GOOG: Roboto,Roboto Light -- /home/username/.fonts/ttf/Roboto-LightItalic.ttf
GOOG: Roboto,Roboto Light -- /home/username/.fonts/ttf/Roboto-Light.ttf
GOOG: Roboto,Roboto Black -- /home/username/.fonts/ttf/Roboto-BlackItalic.ttf
GOOG: Roboto,Roboto Medium -- /home/username/.fonts/ttf/Roboto-MediumItalic.ttf
GOOG: Roboto,Roboto Thin -- /home/username/.fonts/ttf/Roboto-Thin.ttf
GOOG: Roboto -- /home/username/.fonts/ttf/Roboto-Italic.ttf
GOOG: Roboto -- /home/username/.fonts/ttf/Roboto-BoldItalic.ttf
GOOG: Roboto -- /home/username/.fonts/ttf/Roboto-Bold.ttf
PYRS: DAGGERSQUARE -- /home/username/.fonts/otf/DaggerSquare.otf
PYRS: DAGGERSQUARE -- /home/username/.fonts/otf/DaggerSquare-Oblique.otf
```

## Comparison

In the following image, PDFBox export is on the left and Inkscape export on the right, but sourced from the same SVG and font files:

![pdfbox-inkscape](https://user-images.githubusercontent.com/2131950/111083773-550c5b00-84cc-11eb-9137-385edb6a4927.png)

Notice that:

* the word WANTED is discoloured (not a big issue);
* fine lines grid the entire image (especially visible against the WANTED text);
* all text is rasterized;
* the font weight (Roboto thin) is not honoured; and
* the file sizes differ by a fair margin (also not a huge issue).

File sizes:

* inkscape-poster.pdf is 23,481 bytes
* pdfbox-poster.pdf is 493,896 bytes

## Question

How do you force the font subsets to be embedded (to reduce PDF file size and avoid rasterizing glyphs)?

## SSCCE

The SSCCE transcodes /tmp/poster.svg to /tmp/pdfbox-poster.pdf:

``` java
import de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D;
import de.rototor.pdfbox.graphics2d.PdfBoxGraphics2DFontTextDrawer;
import org.apache.batik.anim.dom.SAXSVGDocumentFactory;
import org.apache.batik.bridge.BridgeContext;
import org.apache.batik.bridge.DocumentLoader;
import org.apache.batik.bridge.GVTBuilder;
import org.apache.batik.bridge.UserAgentAdapter;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import static java.awt.RenderingHints.*;
import static java.awt.geom.AffineTransform.getScaleInstance;
import static java.lang.System.getProperty;
import static java.nio.file.FileSystems.getDefault;
import static java.nio.file.Files.newOutputStream;
import static java.nio.file.StandardOpenOption.*;
import static org.apache.batik.util.XMLResourceDescriptor.getXMLParserClassName;

@SuppressWarnings( "SameParameterValue" )
public class Main {
  private static final PdfBoxGraphics2DFontTextDrawer sFontTextDrawer =
    new PdfBoxGraphics2DFontTextDrawer();

  private static final String HOME_USER = getProperty( "user.home", "" );
  private static final String HOME_WINDOWS = getEnvProperty( "WINDIR" );
  private static final List<String> FONT_DIRS = new ArrayList<>();

  static {
    FONT_DIRS.add( HOME_WINDOWS + "/fonts" );

    // MacOS
    FONT_DIRS.add( HOME_USER + "/Library/Fonts" );
    FONT_DIRS.add( "/System/Library/Fonts" );
    FONT_DIRS.add( "/Library/Fonts" );
    FONT_DIRS.add( "/Network/Library/Fonts" );

    // Unix
    FONT_DIRS.add( HOME_USER + "/.fonts" );
    FONT_DIRS.add( HOME_USER + "/.local/share/fonts" );
    FONT_DIRS.add( "/usr/share/fonts" );
    FONT_DIRS.add( "/usr/share/X11/fonts" );
    FONT_DIRS.add( "/usr/X/lib/X11/fonts" );
    FONT_DIRS.add( "/usr/openwin/lib/X11/fonts" );
    FONT_DIRS.add( "/usr/X11R6/lib/X11/fonts" );
  }

  static {
    final var matcher = getDefault().getPathMatcher( "glob:**.{ttf,otf}" );

    for( final var dir : FONT_DIRS ) {
      final Path path = Path.of( dir );

      try( final var walk = Files.walk( path, 10 ) ) {
        for( final var it = walk.iterator(); it.hasNext(); ) {
          final var fontFile = it.next();
          final var fontPath = Path.of( fontFile.toString().toLowerCase() );
          if( matcher.matches( fontPath ) ) {
            System.out.println( fontFile.toFile() );
            sFontTextDrawer.registerFont( fontFile.toFile() );
          }
        }
      } catch( final Exception ignored ) {
        // On Linux, the Windows path won't be found. Safe to ignore this.
      }
    }
  }

  public static void main( final String[] args ) throws Exception {
    // Gain direct access to Batik graphics context.
    final var userAgent = new UserAgentAdapter();
    final var loader = new DocumentLoader( userAgent );
    final var context = new BridgeContext( userAgent, loader );
    context.setDynamic( false );

    // Read the SVG file to render as PDF.
    final var factory = new SAXSVGDocumentFactory( getXMLParserClassName() );
    final var svg = factory.createSVGDocument( "/tmp/poster.svg" );
    final var node = new GVTBuilder().build( context, svg );

    // Ensure that small bounds are enlarged.
    final var bounds = node.getPrimitiveBounds();
    final var w = (float) bounds.getWidth();
    final var h = (float) bounds.getHeight();
    final var scale = (w <= 1 || h <= 1) ? 100 : 1;

    // Create the PDF document model.
    final var pageSize = new PDRectangle( w * scale, h * scale );
    final var page = new PDPage( pageSize );
    final var document = new PDDocument();
    document.addPage( page );

    // Ask Batik to render upon the PDF's graphics context.
    final var graphics = new PdfBoxGraphics2D( document, w, h );
    graphics.setFontTextDrawer( sFontTextDrawer );
    node.setRenderingHints( RENDERING_HINTS );
    node.paint( graphics );
    graphics.dispose();

    // Instruct PDFBox to apply the drawn nodes.
    try( var writer = new PDPageContentStream( document, page ) ) {
      final var xform = graphics.getXFormObject();
      xform.setMatrix( getScaleInstance( scale, scale ) );
      writer.drawForm( xform );
    }

    // Export the PDFBox document to a file.
    final var pdfFile = new File( "/tmp/pdfbox-poster.pdf" );
    final var fos = newOutputStream(
      pdfFile.toPath(), WRITE, CREATE, TRUNCATE_EXISTING );
    document.save( fos );
    document.close();
    fos.close();

    System.out.println( "Created: " + pdfFile );
  }

  private static final Map<Object, Object> RENDERING_HINTS = Map.of(
    KEY_ANTIALIASING, VALUE_ANTIALIAS_ON,
    KEY_ALPHA_INTERPOLATION, VALUE_ALPHA_INTERPOLATION_QUALITY,
    KEY_COLOR_RENDERING, VALUE_COLOR_RENDER_QUALITY,
    KEY_DITHERING, VALUE_DITHER_DISABLE,
    KEY_FRACTIONALMETRICS, VALUE_FRACTIONALMETRICS_ON,
    KEY_INTERPOLATION, VALUE_INTERPOLATION_BICUBIC,
    KEY_RENDERING, VALUE_RENDER_QUALITY,
    KEY_STROKE_CONTROL, VALUE_STROKE_PURE,
    KEY_TEXT_ANTIALIASING, VALUE_TEXT_ANTIALIAS_ON
  );

  private static String getEnvProperty( final String key ) {
    try {
      final var env = System.getenv( key );
      return env == null ? "" : env;
    } catch( final SecurityException ex ) {
      return "";
    }
  }
}
```

Possibly related to issue #10.

**Comment by rototor** [comment]
In this case the main problem is that it’s an Batik issue :(

Batik rasterizes objects/layers as soon as they have any kind of effects on them. In this case you have an opacity-effect.

Nether iText5 nor PDFBoxGraphics2d gets to see any vector shapes here, as Batik will rasterize that before passing down the images to the Graphics2D to paint. As Batik has been unmaintained since 13 (!) years, and only get some minor bugfix releases all 2-3 years (which only include patches submitted from outside to the bug tracker), this is very likely not going to change soon. Someone did a  [Batik fork](https://github.com/css4j/echosvg), but it does not seem to come far yet.

If you remove all opacity settings from the SVG, you are likely going to get a vectorized PDF. But you will never get any embedded text, as Batik is always using the text shapes to draw text. As in SVG you can place text along a path, Batik just always assumes this and gets the text shape, transforms it (if needed) and then paints it.

The "thin" lines between the rasterized tiles are  a rounding issue of your PDF viewer. They will stay as thin as they are independent of the zoom factor. Try using Adobe Acrobat, it will not show this thin lines. (Yes, I saw this already many times in unrelated PDFs; They print fine on e.g a HP Indigo, but may have that issue on an ordinary printer).

I'm sorry, but I don't think I can help you here as the main problem is within Batik.

**Comment by rototor** [comment]
I think it should be possible to make Batik not rasterize with an opacity!=1. It could use an AlphaComposite. But that would require that everything in Batik respects that correctly (also for nested shapes which also may have an opacity setting). Only effects like blur require an rasterized image to be applied on.

Also if no paths are involved in text they could just be rendered using drawText() instead of a shape. 

But as said, nobody is currently working on this.

**Comment by danfickle** [comment]
I looked into this a while ago and I think this may be the core problem:
https://github.com/apache/xmlgraphics-batik/blob/f79ce602fa6244d2a7ff45b57b6a0347e883bc37/batik-gvt/src/main/java/org/apache/batik/gvt/font/AWTGVTGlyphVector.java#L493

Specifically, if it sets `drawGlyphVectorWorks` to false via ancient jre version comparison, it rasterizes everything.

**Comment by DaveJarvis** [comment]
@danfickle, changing the code as follows didn't resolve the issue:

``` java
        if ("11".compareTo(s) >= -4) {
            outlinesPositioned = true;
            drawGlyphVectorWorks = true;
            glyphVectorTransformWorks = true;
        }
```

Looks like it's a deeper issue. I'm closing this because it is unrelated to this library. More feedback is quite welcome!

**Comment by iocoker** [comment]
So, this has been a major issue for us, we even tried the [Batik fork](https://github.com/css4j/echosvg), to no avail. But we discovered a way that works.

Batik goes raster when the shape has `opacity` either in style or as an attribute.

So, instead of applying `opacity`, we changed it to `fill-opacity` and Batik treats it as vector. However, this will imply having to provide a `stroke-opacity` as well if the shape is stroked, but works super fine.
