### ISSUE TITLE
TestPPTXRendering.testPPTXRendering failing with libapache-poi-java from Debian 12

### ISSUE THREAD

**Issue by pgrt** [rototor/pdfbox-graphics2d#43]
Hello,

I am the maintainer of pdfbow-graphics2d in Debian.

Recently the apache-poi java package in Debian was updated for compatibility with XMLBeans 4.0, see commit
  https://salsa.debian.org/java-team/libapache-poi-java/-/commit/66b028467dae6134a7d40aa83f0f27fa0dd2408b

Then TestPPTXRendering.testPPTXRendering in pdfbow-graphics3d began failing, with the message

[ERROR] testPPTXRendering(de.rototor.pdfbox.graphics2d.extendedtests.pptx.TestPPTXRendering)  Time elapsed: 0.197 s  <<< ERROR!
> org.apache.poi.ooxml.POIXMLException: org.apache.poi.ooxml.POIXMLException: org/apache/xmlbeans/metadata/system/s036263A03D2D3FD117889707DB51207A/TypeSystemHolder
> 	at de.rototor.pdfbox.graphics2d.extendedtests.pptx.TestPPTXRendering.testPPTXRendering(TestPPTXRendering.java:30)
> Caused by: org.apache.poi.ooxml.POIXMLException: org/apache/xmlbeans/metadata/system/s036263A03D2D3FD117889707DB51207A/TypeSystemHolder
> 	at de.rototor.pdfbox.graphics2d.extendedtests.pptx.TestPPTXRendering.testPPTXRendering(TestPPTXRendering.java:30)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at de.rototor.pdfbox.graphics2d.extendedtests.pptx.TestPPTXRendering.testPPTXRendering(TestPPTXRendering.java:30)
> Caused by: java.lang.NoClassDefFoundError: org/apache/xmlbeans/metadata/system/s036263A03D2D3FD117889707DB51207A/TypeSystemHolder
> 	at de.rototor.pdfbox.graphics2d.extendedtests.pptx.TestPPTXRendering.testPPTXRendering(TestPPTXRendering.java:30)
> Caused by: java.lang.ClassNotFoundException: org.apache.xmlbeans.metadata.system.s036263A03D2D3FD117889707DB51207A.TypeSystemHolder
> 	at de.rototor.pdfbox.graphics2d.extendedtests.pptx.TestPPTXRendering.testPPTXRendering(TestPPTXRendering.java:30)

You can see the bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1011730 for a bit more information.
By chance, would you have any clue to solve the issue?

Thanks a lot for your attention in any case,

Best regards,
Pierre

**Comment by rototor** [comment]
This is for sure caused by different POI jar versions on the class path. I.e. the jar containing this generated metadata stuff in POI is different as the POI jar itself. It seems to be mixed in some way. Running maven with "-X" would give some hints here what versions are used in what order. I assume that the order is mixed, i.e. oldversion-jar1, newversion-jar2, oldversion-jar2, newversion-jar1 or something like that.

Maybe changing the POI version referenced in the extendedtests/pom.xml to the one packaged in Debian would fix this?

As written earlier - I dropped this test package for the PDFBox 3.0 branch anyway.

If you call maven with ```-pl '!extended-tests'``` it should just skip this module. It's really not needed. Not sure if I just should drop it in the 0.x branch, which targets PDFBox 2.0. In theory it shouldn't matter as nobody should be using this packages, but ...
