### ISSUE TITLE
drawRect does not properly close rectangle

### ISSUE THREAD

**Issue by fransbouwmans** [rototor/pdfbox-graphics2d#46]
When using a drawRect the resulting drawn rectangle looks fine in java, but the resulting pdf export has gaps in the corner points.
When the drawRect is replace by four drawLine calls the rectangle is drawn fine.

![image](https://user-images.githubusercontent.com/652944/190627138-d3b01c50-d0b0-4445-a5aa-027da2aee0bf.png)

![image](https://user-images.githubusercontent.com/652944/190627497-1a884664-1ec1-4b80-a93a-dfbb3de6b515.png)

It is not clear why this happens as the drawRect (not overridden) ultimately calls drawLine itself.

Currently the simple workaround is to use drawLine instead of drawRect

**Comment by rototor** [comment]
This happens because drawRect(int,int,int,int) was defined at a time when there was only some bitmap output for graphics. But depending on your stroke and matrix you are of course getting gabs. In PDF you have "high precission" because you are not aligning on a pixel raster. I.e. that drawLine()'s might not overlap is rather likely on PDFs when you BasicStroke has not at least on 1px width (but what is pixel width in PDF ...)

=> The right fix will be to override drawRect() and do just a draw(new Rectangle2D.Float(...)).

**Comment by rototor** [comment]
I've just released the fix in version 0.42.
