### ISSUE TITLE
InternalDeprecatedCOSCloner causing JPMS module issues

### ISSUE THREAD

**Issue by pjfanning** [rototor/pdfbox-graphics2d#56]
Thanks for the 3.0.0 release. I tried building Apache POI with PDFBox and this lib upgraded to 3.0.0 but the JPMS module-info compile fails in POI. I am no expert in JPMS but I think it is because of the fact that you have a org.apache.pdfbox.multipdf class (InternalDeprecatedCOSCloner). JPMS builds are stricter about packages and generally require that a package is only part of 1 jar and that you don't have 2 jars that have classes in the same package.

The errors look like:

```
/Users/pj.fanning/svn/poi/poi-ooxml/src/main/java9/module-info.java:18: error: module org.apache.poi.ooxml reads package org.apache.pdfbox.multipdf from both de.rototor.pdfbox.graphics2d and org.apache.pdfbox
```

**Comment by rototor** [comment]
I've reopened [PDFBOX-5149](https://issues.apache.org/jira/browse/PDFBOX-5149), please look there for details. This project is not really prepared for JPMS yet...

**Comment by rototor** [comment]
The PDFBox folks don't want issues to reopened, so I create a new one: https://issues.apache.org/jira/browse/PDFBOX-5664

**Comment by rototor** [comment]
PDFBox 3.0.1 was now released with the fix for PDFBOX-5664. I've made the needed adjustments and release PDFBox-Graphics version 3.0.1 - or at least I tried. I think the release should be now on maven central - but the oss.sonatype.org nexus has some at the moment... so the `mvn perform:release` reported some error. But as far as I understand the release with through.

So you can try with JPMS again, should work now.
