### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by JuliuszJ** [rototor/pdfbox-graphics2d#8]
Dear Emmeran,
first I thank for your great job with pdfbox-graphics2d.
I was waiting a long time to generate awesome, vector scalable
charts in PDF. And finally I can be happy to do this using your 
pdfbox-graphics2d with JFreeChart.
Unfortunately after switch from jpeg to vector chart size of result
PDF file increases from 180KB to 800KB. I am using PdfBoxGraphics2DFontTextDrawerDefaultFonts,
so vectorized text is not the source of issue. I found in PDF file a lot of text like _<</BM/Compatible/Type/ExtGState>>_, _R/gs226 4786_ and _0000234965 00000 n_.  The content of PDF file does not change if I switch _compress_ parameter from _true_ to _false_ of the constructor of _PDPageContentStream_. So, it seems _PDPageContentStream_ does not compress graphic generated by pdfbox-graphics2d. Is the any way to force compression? I thank you for any hint which you can provide. Regards, Juliusz.

**Comment by rototor** [comment]
When you use the latest release, the stream is compressed. But currently only using the default compression. See also https://issues.apache.org/jira/browse/PDFBOX-3982

Currently the pdfbox-graphics2d is in the state "it works". But it is not really optimized yet. It always sets the full state (paint, ...) on the stream and also does not reuse ExtGStates (those safe parameters like transparency etc.). 

What JFreeChart chart are you using? I can try to implement reusing the paints used in that chart to save size.

**Comment by JuliuszJ** [comment]
I switched to pdfbox 2.0.8 and pdfbox-graphics2d 0.10-SNAPSHOT, unfortunately still no compression. Regarding JFreeChart I am using _TimeSeriesChart_ .

**Comment by rototor** [comment]
The problem here is not a missing compression. The problem are duplicate ExtGStates.

Think of a PDF as a tree of Map<String,Object> (called Dictionaries). Some of this dictionaries can have a so called content stream. E.g. images have their raw image data as content stream and have map-values like width or height which describe the image. Pages have all the draw commands in the content stream, and have a Resources key which is a map of all resource types and so on. Only the content stream itself can be compressed in a PDF. The dictionaries are not compressed (and can not be compressed). If you want to take a look in a PDF use the PDFBox Debugger - very useful tool. 

Extended Graphics States are a Dictionary of graphics settings located under resources. And pdfbox-graphics2d created a lot of them ... all with the same content.

I've just commited a fix for this. Please pull master and try again.

**Comment by JuliuszJ** [comment]
Great! File size dropped to 180KB. Thank you!

**Comment by rototor** [comment]
I've just released version 0.10 with this fix.
